name: Build and Push Docker Image

on:
  push:
    branches: [main]

jobs:
  docker:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Create .env files
        run: |
          echo "${{ secrets.FRONTEND_ENV }}" > frontend/.env.local
          echo "${{ secrets.BACKEND_ENV }}" > backend/.env
        shell: bash


      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .                      # root context - all your folders
          file: docker/Dockerfile         # path to your Dockerfile inside docker/
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/movies:latest
